### PR TITLE
feat: support must.TLSConfig()

### PR DESCRIPTION
**Pull request by TomerSalton**
add support for must.TLSConfig().

### CODE REVIEW

**Comment by misha-ridge** [comment]
This change is [Reviewable](https://reviewable.io/reviews/ridge/must/11)

**Review by misha-ridge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ridge/must/11)* status: 1 of 1 file unreviewed; 1 unresolved discussion (waiting on @dottedmag, @feldgendler, and @TomerSalton)

___
*[types_gen.go, line 1 at r1](https://reviewable.io/reviews/ridge/must/11#-Ms0r7ZKD9-K5XZAWR7p:-Ms0r7ZL8eDtZCzUxJtq:b-ai9mrt) ([raw file](https://github.com/ridge/must/blob/06cd02febbb2a59caa5f4b0b6985d228deef6358/types_gen.go#L1)):*
> ```Go
> // Code generated by github.com/ridge/must/generator. DO NOT EDIT.
> ```

I don't see a change to the generator

**Review by feldgendler — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ridge/must/11)* status: all files reviewed; 1 unresolved discussion (waiting on @TomerSalton)

**Review by TomerSalton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ridge/must/11)* status: 2 of 2 files unreviewed; 1 unresolved discussion (waiting on @dottedmag, @feldgendler, and @misha-ridge)

___
*[types_gen.go, line 1 at r1](https://reviewable.io/reviews/ridge/must/11#-Ms0r7ZKD9-K5XZAWR7p:-Ms12w-H2Oy8maFXn6Lc:b-dlr0rn) ([raw file](https://github.com/ridge/must/blob/06cd02febbb2a59caa5f4b0b6985d228deef6358/types_gen.go#L1)):*
<details><summary><i>Previously, misha-ridge (Misha Gusarov) wrote…</i></summary><blockquote>

I don't see a change to the generator
</blockquote></details>

Ah, I didn't really understand how this package works.
Sorry.

**Review by feldgendler — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ridge/must/11)* status: all files reviewed; 1 unresolved discussion (waiting on @misha-ridge)

**Review by feldgendler — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ridge/must/11)* status: all files reviewed; 1 unresolved discussion (waiting on @misha-ridge)

**Review by misha-ridge — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ridge/must/11)* status: :shipit: complete! all files reviewed; all discussions resolved

**Pull request merged**
